language: ruby

rvm: 2.5.1

script: rake test && rake rdoc

deploy:
  skip_cleanup: true
  provider: rubygems
  api_key:
    secure: lAwhXcAsxPQxz6dJqC8/Jr+jneKOGY/nrAiJ6TQckAk2xVOzJnYyQ8UYbk77Z9ATp34xZGRO4hD6fzWXB/Hm74AdkKfb4Bdmw+f9f2CAtpUJk+QAba9gasgQL3bXlsBNNjm7IoAh6k1aBs8cRtrySbvSZt86Sokp6k8TZj21iXQl9V/OPjr35u1WkDqOl+88FHZKj7Iq31c6Fic5fTHLv2F235ICxE7fVn4WNq0mZm2Suwdk5+MPn8l23Mqy13RNcR8jOgYcJ0s4SEUe7XQFJrIqb1A9gJ4npBdZGcMRb48aFYRsxI1xA+jRGtv7IzWolo5FhmhEoMcbEzb+CoRHTBMe2ArOtJz2E+R9V0L2jyYVRx4wMiLrE66FaL+9lCpWQibUKfUDvIvAF7iiwYbICCy5vfz2uT43D/iXHUw6Lt3bcJIojNSUmWvkUnOVFG6Cg8LltxmTuacqoRi2wKBtNYA9+qn0zJmns8BmQOEi1hxpp/fmmFdeEmQinjF2sL9KyRqnLjSK1TC4C/GQ3LBA4p2X143z4Ld/hyWf5qF5xcEyO0EgwHNDBVX9DdKvjVOKxeagZfFjgm3eD2xjEo9oW409Kwd8PdxXi9Cbfn7YD80MBzDfYu3F8zSJYWwkRo73FAcr2G++DZ0HLsA/p3R90jqGfBnkxNmYnv5UHG/bYkk=
