language: ruby
rvm: 2.2.0
script: rake test && rake rdoc
deploy:
  provider: rubygems
  api_key:
    secure: GmjPqi3M9sP0WI+fBDvn+RK2+Yn1WpEcG8Mlkw6IKBRtNoll15QAyJoxusueyNbSQS/xjJH+oaL2KK2BzEofsGDQdmhX54riQBpkQ25r9kLSUqozSDKhGmA3YCGUp3UkhrQTYyubRee33eHb7IKyx3/VlDUY8bmKNsOLRN3yyIDQ9qw4gVq5lzMrJwycNy+WYRoSpDmysrswzPx4fggdvTOpgbB7BWnlisrjcuR2B7cJS/Cfy6MZeBz2xBCxJuuhVd6B4RRI1avAbSvA8gPHg0mKhJ8PDyln9P5VnV2KLiwOGe+hXTO9vl1PTHd8eCUMl1NZGRc0NeTZFikhTH908ouZWSlnle5pKeos+Mls7+Fj9YsEXnvzqOl8IEOvtCdSkNj5F6O0iqAYhqw5kU/0Z4HbX+pJzmGFtEvJrJwZsNRkvnEEwZVReOKjaVt8bsvhqYHnDQr0MnmN1nQYTLAYBBPGSufqqelRVZISOp9EiJFcWteLmysBYwjNQ4mvF1RrqxAvuMAgVRQvJ2qaKQbkboOylfQIFfsN/eQUEqJOi0HaHdeBqsQGuJiHfEMvY+k+jyRRemAVbkJgFwOaJUKS06n5bdA4PhriR0KKvGBYv1KofjLFvZmUbqcE3dkjihMVYiv+TyHMNAb04M7nT3ALzvHwMAQ713S08GjjSAEkKFw=
  gem: hitsuji
  on:
    tags: true
    repo: realtable/hitsuji
